### ISSUE TITLE
Can't change domain name

### ISSUE THREAD

**Issue by lugosieben** [ctih1/frii.site-frontend#142]
**Describe the bug**
It's impossible to change the name of an existing domain.

**To Reproduce**
1. Go to dashboard
2. Try to change the name of one of your domain
3. Hit save
4. See error:
Could not modify mc (my domain name that i changed it to)
Please make sure you own the domain.

**Additional information:**
 - Browser Safari
-  Device Phone, Tablet
-  OS iOS

**Comment by ctih1** [comment]
Todo: implement domain re-registration while saving the DNS settings

**Comment by ctih1** [comment]
Implementing temporary fix: making the domain input field disabled
