### ISSUE TITLE
German translation incorrect grammar on index

### ISSUE THREAD

**Issue by ctih1** [ctih1/frii.site-frontend#146]
"Erhalte jetzt deinen kostenlosen subdomain" -> "Erhalte jetzt deine kostenlose subdomain"

![image](https://github.com/user-attachments/assets/af55ac7a-2ad4-4d29-a784-4a82ac732b1f)

Thanks' in advance!

**Comment by Planethac** [comment]
so the translation seems to be off pretty much everywhere

**Comment by Planethac** [comment]
On The signup from:
"Forgot your Password": "Passwort vergessen?"
"Stattdessen Registrieren": "Registrieren" (That not wrong but usally its done likem this)
