### ISSUE TITLE
Domain Register Bug

### ISSUE THREAD

**Issue by duckopia** [ctih1/frii.site-frontend#155]
I accidentally deleted a domain that i still need to use. After that, I tried to register my domain again but it always output: 
![image](https://github.com/user-attachments/assets/9bbc9f2f-de3c-4bd6-9b7a-b9f0284fbabf)
But there is no domain registered
![image](https://github.com/user-attachments/assets/596378f8-473e-41c1-bf73-71e4899cdf2e)

**Comment by ctih1** [comment]
Could you give us your username? Keep in mind this is case sensitive

**Comment by ctih1** [comment]
Potentially related to #145

**Comment by ctih1** [comment]
@duckopia We are still investigating this, in the meanwhile, we have deleted the domain from our system, and it is free to register.

**Comment by duckopia** [comment]
Solved, tksm!
