### ISSUE TITLE
Password reset doesn't work (at least for me i think)

### ISSUE THREAD

**Issue by rock3tsprocket** [ctih1/frii.site-frontend#157]
**Describe the bug**
Resetting your password doesn't work (it says it did but it doesn't actually change it, unless it takes a long time to do so)

**To Reproduce**
1. Sign out if required
2. Click on the 'Account' tab
3. Reset your password
4. Try to log in with said password

**Expected behavior**
Password gets reset

**Actual behaviour**
Password doesn't reset

**Screenshots**
![image](https://github.com/user-attachments/assets/23a31046-ce1b-4ff1-bae4-548ac9ce3b26)

![image](https://github.com/user-attachments/assets/2a3263d5-75a4-427d-8336-974dfaf24828)

**Additional information:**
 - Browser: Mozilla Firefox
-  Device: Desktop
-  OS: Linux Mint
-  OS Version: 20
-  Device resolution: 1280x1024

**Additional information**
The password in the password recovery screen isn't censored

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by rock3tsprocket** [comment]
dude what does a compiler have to do with a password recovery problem

**Comment by ctih1** [comment]
This is definitely a bug.  A password reset doesn't take a long time, and should be instantaneous. Potentially related to caching issues? Does the same problem happen when you try to login after a minute?

**Comment by ctih1** [comment]
Keep in mind that the username is case sensitive

**Comment by rock3tsprocket** [comment]
> Keep in mind that the username is case sensitive

well i tried using RockPie as the username to recover and that gave me an error saying the username is invalid

**Comment by rock3tsprocket** [comment]
> This is definitely a bug. A password reset doesn't take a long time, and should be instantaneous. Potentially related to caching issues? Does the same problem happen when you try to login after a minute?

tried deleting my frii.site cache, nothing.

**Comment by ctih1** [comment]
Have you overwritten your `server_url` variable in your localStorage?

**Comment by rock3tsprocket** [comment]
i solved it for me by just implanting the token from my laptop onto my desktop

**Comment by ctih1** [comment]
Issue doesn't seem to be fixed, will investigate after solving #145

**Comment by ctih1** [comment]
Closed - can't replicate.

**Comment by rock3tsprocket** [comment]
never mind it works, guess the site had some beef with Linux Mint.
