### ISSUE TITLE
Not being able to modify domains, domain table not loading and registering domains throws an unhandled error

### ISSUE THREAD

**Issue by rock3tsprocket** [ctih1/frii.site-frontend#159]
I can't modify any domains, whether i'm changing their record type, their content or deleting them.

**Comment by ctih1** [comment]
Do you get an error?

**Comment by rock3tsprocket** [comment]
no

**Comment by ctih1** [comment]
Does this happen with all domains?

**Comment by rock3tsprocket** [comment]
Now they don't load at all.

**Comment by ctih1** [comment]
Can you see anything in the developer console?

**Comment by ctih1** [comment]
Might sound stupid, but do you own domains?

**Comment by rock3tsprocket** [comment]
Yes

**Comment by ctih1** [comment]
It is most likely that you
A): don't have domains (as a result of potentially signing into the wrong account) 
B): have the server_url override set to something other than our support servers.

You can check A by going to your account settings, and clicking "download your data". If you see that the "domains" part is empty ("domains":{}), it means that you haven't registered any domains

**Comment by rock3tsprocket** [comment]
> It is most likely that you A): don't have domains (as a result of potentially signing into the wrong account) B): have the server_url override set to something other than our support servers.
> 
> You can check A by going to your account settings, and clicking "download your data". If you see that the "domains" part is empty ("domains":{}), it means that you haven't registered any domains

So I actually don't have domains but i'm not on the dev server, and creating a domain results in an unhandled error. I tried clearing the local storage but that didn't do anything. Also are you sure you deleted 200947e34506d98e529af6cdd8bb0924ce9dcc8710d946424c7c09af4763ee5c?

**Comment by rock3tsprocket** [comment]
Oh for further context, the domain table is stuck with an infinite blur, possibly related to https://github.com/ctih1/frii.site-frontend/commit/c500b6264095cc0f95f23068330cf0bf7b4a7e21

**Comment by ctih1** [comment]
Linked to #180

**Comment by ctih1** [comment]
Fixed in Dev (canary)
