### ISSUE TITLE
Pruchaching domains on https://www.frii.site/store does not work.

### ISSUE THREAD

**Issue by Rage65** [ctih1/frii.site-frontend#174]
When you navigate to the page it loads fine but when you press purchase it does nothing. I checked the js console and its not even throwing errors.

**Comment by ctih1** [comment]
Are you on mobile or desktop?

**Comment by rock3tsprocket** [comment]
It's impossible to replicate this due to the fact that going there makes you sign in even if you're signed in

**Comment by Rage65** [comment]
> Are you on mobile or desktop? 

Desktop

**Comment by Rage65** [comment]
> It's impossible to replicate this due to the fact that going there makes you sign in even if you're signed in

Yeah that's what I thought but I just wanted to throw it out there

**Comment by ctih1** [comment]
> It's impossible to replicate this due to the fact that going there makes you sign in even if you're signed in

That would be due to lacking permissions to use the credit store, which is still in beta

**Comment by rock3tsprocket** [comment]
> That would be due to lacking permissions to use the credit store, which is still in beta

oh

**Comment by Rage65** [comment]
> > It's impossible to replicate this due to the fact that going there makes you sign in even if you're signed in
> 
> That would be due to lacking permissions to use the credit store, which is still in beta

I do have the perms. Yoy granted them to me right?

**Comment by ctih1** [comment]
#182 Closes this. Please use canary.frii.site until dev is merged into master.
