### ISSUE TITLE
Domain still registered after account deletion

### ISSUE THREAD

**Issue by Isaac-D20** [ctih1/frii.site-frontend#197]
So I had two records registered - CNAME and TXT - for a certain subdomain.
At some point, I wanted to delete the TXT record, so I switched over to the canary.frii.site as recommended.
After deleting the TXT record I switched back to the www site, and the CNAME was gone too. Was that supposed to happen?
Anyway, I tried re-registering the subdomain, and it failed, saying it is already registered.
Lastly, I tried deleting my account hoping the subdomain would go away with it, but no dice - after recreating an account the subdomain remains already registered.

1. Register a new subdomain
2. Delete the current account
3. Create another account
4. Try to register the same subdomain

**Expected behavior**
Registered subdomains should get deleted upon deletion of the account tied to it.
And if the CNAME disappearance is also an issue, then it might need to be looked into as well.

**Additional information:**
 - Browser: Edge
-  Device: Acer Aspire 5
-  OS: Windows 11
-  Device resolution: 1920x1080

**Comment by ctih1** [comment]
What's the username for your account? If you don't feel comfortable sharing it here, you can email us at support@frii.site

**Comment by ctih1** [comment]
> After deleting the TXT record I switched back to the www site, and the CNAME was gone too. Was that supposed to happen?

No, this was not supposed to happen

**Comment by ctih1** [comment]
The issue with deleting domains fixed in dev, investigating the CNAME deletion
