### ISSUE TITLE
psl support :(

### ISSUE THREAD

**Issue by sctech-tr** [ctih1/frii.site-frontend#198]
**Describe the bug**
there is no psl support so cloudflare does not accept the domain and says "make sure you're providing a domain, not a subdomain", making ns records useless
**To Reproduce**
try adding a frii.site domain to cloudflare dns
**Expected behavior**
i expected cloudflare to accept the domain
**Screenshots**
no

**Additional information:**
 - Browser: everything
-  Device: everything
-  OS: everything
 - OS Version: everything
-  Device resolution: everything

**Additional context**
see https://github.com/publicsuffix/list

**Comment by ctih1** [comment]
Unfortunately we do not meet the standards for their requirements; specifically user count, and 2 year registration policy

**Comment by ctih1** [comment]
Note: if cloudflare support is due to the API, you can use ours. If you need more records, you can get some for free if you contact our support department (support@frii.site) :)
