### ISSUE TITLE
Add translation framework

### ISSUE THREAD

**Issue by lugosieben** [ctih1/frii.site-frontend#72]
I don't know if this is in the projects scope, but my suggestion is to add a translation framework (e.g. i18n). I would do it myself but I have no clue about Svelve.

If a translation framework is added, I would be happy to contribute the german translation!

**Comment by ctih1** [comment]
Hello Lugo! Adding a translation framework is something I've been looking to do for a while, and is definitely in the projects scope. I'll try to implement this in the near-ish future, I'll post updates here! 🙂

**Comment by ctih1** [comment]
I'll implement documentation for this later tonight
