### ISSUE TITLE
HTML tags not properly rendered

### ISSUE THREAD

**Issue by lugosieben** [ctih1/frii.site-frontend#81]
**Describe the bug**
HTML tags in translations are shown as text instead of HTML tags.

**To Reproduce**
1. Go to any page where there is a HTML tag in the translation
2. See error

**Expected behavior**
Text should be wrapped in a tag

**Screenshots**
![image](https://github.com/user-attachments/assets/ed8eb774-bd29-471a-8e9b-b4047742b004)

**How to fix**
See the `@html` tag in [this](https://svelte.dev/repl/de39de663ef2445b8fe17b79c500013b?version=3.33.0) example

**Comment by ctih1** [comment]
Thanks for the bug report!
